"""empty message

Revision ID: 3c49e0eb3379
Revises: b192bb74ff0b
Create Date: 2017-07-11 22:39:07.913038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c49e0eb3379'
down_revision = 'b192bb74ff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_token', sa.String(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'github_token')
    # ### end Alembic commands ###
