"""empty message

Revision ID: b192bb74ff0b
Revises: fb06e94f5588
Create Date: 2017-07-11 22:09:03.438565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b192bb74ff0b'
down_revision = 'fb06e94f5588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['github_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'github_id')
    # ### end Alembic commands ###
